### ISSUE TITLE
Bug in getting a name from a user for display

### ISSUE THREAD

**Issue by zwarthoorn** [EDM-Spot/OtterBot#1]
i saw a wierd issue when somboddy used the command !commands it does not pick up the user correctly and trows a @undifiend
![schermafbeelding 2018-10-03 om 09 10 23](https://user-images.githubusercontent.com/5434531/46395609-2e3b7f00-c6ed-11e8-98fe-e6b6b3a62f80.png)

**Comment by Mrcl1450** [comment]
Fixed
